### ISSUE TITLE
compile issue on ubuntu 20.04

### ISSUE THREAD

**Issue by loser885** [gagax1234/OpenFunscripter#1]
[ 99%] Building CXX object src/CMakeFiles/OpenFunscripter.dir/UI/OpenFunscripterVideoplayer.cpp.o                                                                       
In file included from /home/losername/OpenFunscripter/src/Funscript/Funscript.h:8,
                 from /home/losername/OpenFunscripter/src/ScriptingMode.h:3,
                 from /home/losername/OpenFunscripter/src/OpenFunscripter.h:10,
                 from /home/losername/OpenFunscripter/src/UI/OpenFunscripterVideoplayer.cpp:3:
/home/losername/OpenFunscripter/src/UI/OpenFunscripterVideoplayer.cpp: In member function ‘void VideoplayerWindow::MpvEvents(SDL_Event&)’:
/home/losername/OpenFunscripter/src/UI/OpenFunscripterVideoplayer.cpp:105:16: warning: format ‘%d’ expects argument of type ‘int’, but argument 4 has type ‘int64_t’ {aka ‘long int’} [-Wformat=]
  105 |     LOGF_DEBUG("Property \"%s\" has changed to %d", prop->name, *(int64_t*)prop->data);
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~              ~~~~~~~~~~~~~~~~~~~~~
      |                                                                 |
      |                                                                 int64_t {aka long int}
/home/losername/OpenFunscripter/src/OpenFunscripterUtil.h:34:76: note: in definition of macro ‘LOGF_DEBUG’
   34 | GF_DEBUG(format, ...) SDL_LogDebug(SDL_LOG_CATEGORY_APPLICATION, format, __VA_ARGS__)
      |                                                                  ^~~~~~

/home/losername/OpenFunscripter/src/UI/OpenFunscripterVideoplayer.cpp:105:49: note: format string is defined here
  105 |     LOGF_DEBUG("Property \"%s\" has changed to %d", prop->name, *(int64_t*)prop->data);
      |                                                ~^
      |                                                 |
      |                                                 int
      |                                                %ld
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-writable-strings’
[ 99%] Building CXX object src/CMakeFiles/OpenFunscripter.dir/UI/ScriptSimulator.cpp.o
[ 99%] Building CXX object src/CMakeFiles/OpenFunscripter.dir/event/EventSystem.cpp.o
[100%] Building CXX object src/CMakeFiles/OpenFunscripter.dir/imgui_impl/imgui_impl_opengl3.cpp.o
[100%] Building CXX object src/CMakeFiles/OpenFunscripter.dir/imgui_impl/imgui_impl_sdl.cpp.o
[100%] Linking CXX executable ../../bin/OpenFunscripter
/usr/bin/ld: CMakeFiles/OpenFunscripter.dir/imgui_impl/imgui_impl_opengl3.cpp.o: undefined reference to symbol 'glEnable'
/usr/bin/ld: /lib/x86_64-linux-gnu/libGL.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/OpenFunscripter.dir/build.make:346: ../bin/OpenFunscripter] Error 1
make[1]: *** [CMakeFiles/Makefile2:1162: src/CMakeFiles/OpenFunscripter.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by gagax1234** [comment]
So I can say the project compiles right now on my fedora 31 system with clang and gcc.
You could try uncommenting this in the lib/CMakeLists.txt
```cmake
# ============
# == OPENGL ==
# ============
set(OpenGL_GL_PREFERENCE "GLVND")
find_package(OpenGL REQUIRED)
```
and then add `${OPENGL_LIBRARIES}` like this in src/CMakeLists.txt

```cmake
target_link_libraries(${PROJECT_NAME} PUBLIC
  nlohmann_json
  imgui
  imgui_stdlib
  glad
  SDL2-static
  SDL2main
  portable_file_dialogs
  ${OPENGL_LIBRARIES}
)
```
And then regenerate the cmake.

**Comment by loser885** [comment]
thank you for the assistance
the compile has less error output now

[100%] Linking CXX executable ../../bin/OpenFunscripter
/usr/bin/ld: CMakeFiles/OpenFunscripter.dir/imgui_impl/imgui_impl_opengl3.cpp.o: undefined reference to symbol 'glEnable'
/usr/bin/ld: /lib/x86_64-linux-gnu/libGL.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/OpenFunscripter.dir/build.make:346: ../bin/OpenFunscripter] Error 1
make[1]: *** [CMakeFiles/Makefile2:1162: src/CMakeFiles/OpenFunscripter.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by gagax1234** [comment]
Damn I was hoping this would fix it.
I tried compiling on a fresh ubuntu 20.04 vm and had no issues.
I cloned the repository ran `git submodule update --init --recursive`
then I installed `sudo apt install build-essential cmake libmpv-dev`.
I created a build directory, ran `cmake ..` from inside the directory and then `make` and it compiled and linked fine.

I think it has something to do with your system/drivers.
Maybe this helps http://techtidings.blogspot.com/2012/01/problem-with-libglso-on-64-bit-ubuntu.html

**Comment by loser885** [comment]
it built in a vm for me as well, must be a local issue on both of my machines

**Comment by loser885** [comment]
the build in virtualbox does compile, but segfaults
does your ubuntu vm build execute?

**Comment by gagax1234** [comment]
> the build in virtualbox does compile, but segfaults
> does your ubuntu vm build execute?

No it actually didn't. 😅 I just tested it again. 
It worked after additionally installing `libglvnd-dev` though!

**Comment by loser885** [comment]
it works :)
