### ISSUE TITLE
Metadata Prompt on New Scripts

### ISSUE THREAD

**Issue by defucilis** [gagax1234/OpenFunscripter#13]
Copying a post from EroScripts over to here on Sentinel's recommendation:

We were talking in [this thread](https://discuss.eroscripts.com/t/metadata-information/20758/11) about how it would be good if more creators added metadata. I was thinking it might be nice if, upon starting a new script, OFS presented a dialog to the user prompting them to add metadata right then and there (with a ‘skip for now’ button, of course!)

I feel like that would encourage more people to include metadata, which would make it possible to use that metadata in various application UIs and whatnot!

**Comment by gagax1234** [comment]
What I'm going to do is on project creation just popup the metadata editor.
I'm also changing it to be a popup modal which means you're not going to be able to do anything until you close it again.
This is as much annoyance as I'm willing to add but should definitely have the desired nudging effect. 😁

**Comment by defucilis** [comment]
Yeah I reckon that'll do the job perfectly!

**Comment by gagax1234** [comment]
https://github.com/gagax1234/OpenFunscripter/releases/tag/1.2.0
