### ISSUE TITLE
Renaming project file

### ISSUE THREAD

**Issue by Lucifie** [gagax1234/OpenFunscripter#17]
I have just noticed that if I rename the project file and the video that OFS still shows the old video name in the player in the right lower corner (1.2.0). It had asked me to select a new video when i reopened OFS but afterwards its still showing the old name.

After updating to 1.2.1 i had to create a new test project. I have deleted the old project file and dropped the video again. OFS then showed my old script which was nice but where it got those data when the project file was deleted before?

**Comment by gagax1234** [comment]
> OFS then showed my old script which was nice but where it got those data when the project file was deleted before?

If there's funscripts with the same directory starting with the same name they'll get automatically imported.

What you're describing is already possible.
"Project"->"Configure" you can change the default paths which will also update the title that is displayed.

It's completely independent of where you store the project file or what it's named.
