### ISSUE TITLE
Negative backup time

### ISSUE THREAD

**Issue by Lucifie** [gagax1234/OpenFunscripter#19]
Just open OFS without a script and you can see it.
![grafik](https://user-images.githubusercontent.com/81717113/116811950-57924500-ab4c-11eb-826f-39fe323a8abd.png)

**Comment by gagax1234** [comment]
Yeah aware of that one.
Normally I woudn't have bothered since it doesn't do any harm.
But since you bothered creating an issue I guess I'll fix it... 🙃
