### ISSUE TITLE
Implement Gamepad support

### ISSUE THREAD

**Issue by ExtraXX** [gagax1234/OpenFunscripter#2]
Hey, thanks for making an opensource option.
I'm currently using JoyFunScripter cause I use the gamepad (tried Frame By Frame but didn't get good results).

I'm creating this issue to track the addition of Gamepad support.
Just FYI, I'm currently using an Xbox360.

Thanks!

**Comment by gagax1234** [comment]
This is the next thing I'm going to tackle.

Just to clarify though, gamepad support would mean you'd be able to script without touching the keyboard or the mouse (or at least reducing it to a minimum).
So basically I'm allowing key bindings to be bound to a controller or is there something I'm not thinking of?

Have you checked out the recording mode? You are already able to script using a controller.

**Comment by ExtraXX** [comment]
Ah, got it. I was using version 1.0.5 which didn't have that option.
I can use it with the gamepad now.

I cannot however, replace the key bindings with the controller button as to be able to pause, get back, start recording, select, delete., etc..
IT would be great to be able to do it without having to interact with the keyboard.

Thanks.

**Comment by gagax1234** [comment]
There's a new release which includes controller support.
https://github.com/gagax1234/OpenFunscripter/releases/tag/1.0.8

**Comment by gagax1234** [comment]
Closing this.
