### ISSUE TITLE
Select very much top points and you can shift them too far

### ISSUE THREAD

**Issue by Lucifie** [gagax1234/OpenFunscripter#25]
This stays so even after reloading the project file.
Selecting top or bottom points is then not working anymore.
If I execute my Select-PointsToSkip lua script then OFS recalculates the lines and corrects it even if no point is selected.
![grafik](https://user-images.githubusercontent.com/81717113/118881814-c6fd8800-b8f3-11eb-8e05-7aa8c07550ed.png)

**Comment by gagax1234** [comment]
I looked at the move code and it actually assumed that the selection is whole without holes. 🙃
It's fixed now but  doesn't prevent the order from changing.

The reason the Lua script fixed it is because it always sorts the actions.
