### ISSUE TITLE
Spline Interpolation

### ISSUE THREAD

**Issue by CharlesMcBaker** [gagax1234/OpenFunscripter#4]
I just tetsed your subtitler, fanatastic work!

EDIT: I see you added spline interpolation, but it gives weird results.
You should try to use Cubic or Catmull-romm. 
 

I've also attached a easy-to-use spline c++ library you can use with vectors.
https://kluge.in-chemnitz.de/opensource/spline/

I've tested this libary for this usecase and it works extremely well, see attached video.

------------------------------------------------------
We will add support to the Keon, where the whole subtitle/script keypoints can be loaded in the device memory.
And local spline interpolation happens within the Keon's microcontroller.

The advantage is that only time needs to be synced periodically over BT. 
And we can achieve extremely smooth & accurate motion without exessive BT communication.

**charlie@kiiroo.com**

[spline.txt](https://github.com/gagax1234/OpenFunscripter/files/5826414/spline.txt)

https://user-images.githubusercontent.com/18519755/104849092-40ef1780-58e8-11eb-86e7-202bd616a8a9.mp4

**Comment by gagax1234** [comment]
Yes technically what I called "Spline mode" just adds easing between the points. https://easings.net/#easeInOutCubic
I'll look into the library you posted and see if I can make it more sophisticated. Either way this is purely visual and doesn't generate any extra points in the saved funscript.

**Comment by gagax1234** [comment]
I tried the library you posted but wasn't happy with the results (probably something I was doing wrong?) for long strokes the spline would always overshoot and I would have to clamp the values which looked wrong.
Anyway I have glm already in the project and noticed that glm had some spline functions.
I've written my own spline around [glm::catmullRom](http://glm.g-truc.net/0.9.8/api/a00229.html) which works great.

If you want to check it out ASAP there's these builds.
https://ci.appveyor.com/project/gagax1234/openfunscripter/builds/37388074/artifacts
Note: The Spline rendering moved to a right click context menu on the timeline.
I'm going to make spline rendering the new default for the next release.

I'll keep this issue open til the next tagged release.

**Comment by gagax1234** [comment]
There's now a tagged release: [1.1.5](https://github.com/gagax1234/OpenFunscripter/releases/tag/1.1.5)
