### ISSUE TITLE
Option to Lock the Video into place for easy scripting with a graphics tablet.

### ISSUE THREAD

**Issue by JH1979** [gagax1234/OpenFunscripter#5]
Hi Gagax1234, I am Gandalf on Eroscripts, I would like to know if it would be possible to add an Option in the View-Tab of the Menu to fix the Video Size and Position if checked or possibly the Whole Layout excluding the Simulator?
I am new to the Whole Scripting Game, 
but I find it the most Comfortable if I am scripting on the Fly with a Stylus of my Graphics Tablet, 
unfortunately if I touch the Tablet with the Tip of the Pen/Stylus the Video gets grabbed and moved 
because it's acting like a mouse click.

I am asking because scripting with the Mouse is not great, with a Joypad is very inaccurate and with a Keyboard is really slow,
and these Graphics Tablets are pretty cheap these days, got mine for 40 or 50€, can't remember.

**Comment by gagax1234** [comment]
That's an easy addition but wouldn't you want to lock the simulator in this scenario as well?
I'm going to add both a way to lock the video aswell as simulator.

Also thanks for obliging my request to do this over github.
Creating a github account just for this is annoying but the point is to keep this out of the eroscripts thread which has benefits for everyone.
The only thing you did wrong was to post this redundantly on eroscripts as well. 😅

**Comment by gagax1234** [comment]
I added it, there's now a lock checkbox in the simulator window and the video player has a right click context menu with a "Lock" button.
I've decided to not add an entry to the "View" menu as it already very bloated imo.

**Comment by gagax1234** [comment]
There's now a tagged release: [1.1.5](https://github.com/gagax1234/OpenFunscripter/releases/tag/1.1.5)
