### ISSUE TITLE
TCode crashing ESP32

### ISSUE THREAD

**Issue by f86k** [gagax1234/OpenFunscripter#7]
How is TCode serial handled differently than in XTPlayer or JoyFunPlayer? I am using a ESP32 with the OSR 2.2 TCode sketch and OFS causes the ESP32 to crash/reset as soon as a stroke is sent (e.g. when hitting a point on the script or clicking the "Home" button). XTPlayer and JoyFunPlayer work fine.

**Comment by f86k** [comment]
Interestingly this happens regardless of what program is loaded actually, it will crash it even if there is nothing related to TCode loaded onto the ESP32.

**Comment by gagax1234** [comment]
> How is TCode serial handled differently than in XTPlayer or JoyFunPlayer?

How would I know?

I didn't get what is crashing? OFS or the OSR?
I'm not familiar with this ESP32.
Can you check if this issue persist in this version?https://ci.appveyor.com/project/gagax1234/openfunscripter/builds/37643961/artifacts

**Comment by f86k** [comment]
> How would I know?

Sorry, I didn't realize that XTPlayer and JoyFunPlayer weren't open source, haha

> I didn't get what is crashing? OFS or the OSR?

The OSR board is crashing, not OFS. 

> I'm not familiar with this ESP32.

So the ESP32 is a processor that is used on development boards, and you can compile Arduino code onto these boards. In this case the ESP32 board is just replacing whatever Arduino board you would use with the OSR.

> Can you check if this issue persist in this version?

The issue persists in that build. Whenever the script is playing, the ESP32 board constantly resets. If the script is paused, the board is fine and does not reset. 

I got this program called "Serial Port Monitor" from Eltima and I may have found the problem:
This is the OFS log:
![image](https://user-images.githubusercontent.com/76853493/107155745-b8402600-693f-11eb-8e0d-be8649510b52.png)


This is the JoyFunPlayer log:
![image](https://user-images.githubusercontent.com/76853493/107155756-caba5f80-693f-11eb-9265-0d20391cbd57.png)

Looks like that blue stuff is some sort of check/waiting on serial.

**Comment by gagax1234** [comment]
Oh wow I would've never thought of doing that.
However the weird thing is when I do the same thing I don't get that blue stuff in JoyFunPlayer I only get the grey writes.

There's a couple settings I can set baud rate which is 115200, data bits, stop bits, parity & flow control from what I could tell those settings matched with JFP (I'm unsure about flow control).
It doesn't help that I'm very clueless to be honest when comes to serial communication.

Grasping straws here. I set flow control from none to hardware 🤷‍♂️  maybe that does something.
I'll revert it if it didn't.
https://ci.appveyor.com/project/gagax1234/openfunscripter/builds/37654910/artifacts

**Comment by f86k** [comment]
> Grasping straws here. I set flow control from none to hardware b61aeab 🤷‍♂️ maybe that does something.

It seemed to break it entirely, it couldn't write to serial and nothing happened to the ESP32 (no crash but also no input).

Also it looks like the blue checks are not required since they did not show up with XTPlayer.
![image](https://user-images.githubusercontent.com/76853493/107167912-bf872400-697f-11eb-9adf-64322e26a8ad.png)

I logged what happens when OFS, XTPlayer, and JoyFunPlayer connect. Hopefully this holds the answer because XTPlayer works and its output looks basically identical to OFS's during script playback (only gray stuff), so I think it's the start-up stuff during the connection that make the difference.

[**seriallogs.zip**](https://github.com/gagax1234/OpenFunscripter/files/5940931/seriallogs.zip)

There are things missing from the OFS log that exist in the JFP log, like

- IRP_MJ_READ
- IRP_MJ_DEVICE_CONTROL (IOCTL_SERIAL_GET_COMMSTATUS)
- IRP_MJ_DEVICE_CONTROL (IOCTL_SERIAL_SET_WAIT_MASK)
- IRP_MJ_DEVICE_CONTROL (IOCTL_SERIAL_WAIT_ON_MASK)
- IRP_MJ_DEVICE_CONTROL (IOCTL_SERIAL_PURGE)
- IRP_MJ_DEVICE_CONTROL (IOCTL_SERIAL_SET_QUEUE_SIZE)
- IRP_MJ_DEVICE_CONTROL (IOCTL_SERIAL_GET_PROPERTIES)
- IRP_MJ_DEVICE_CONTROL (IOCTL_SERIAL_GET_MODEMSTATUS)

The MJ_READ, COMMSTATUS, MODEMSTATUS, SET_WAIT_MASK, and WAIT_ON_MASK stuff shows up in the XTPlayer log too so those could be the important missing things from OFS's serial.

**Comment by gagax1234** [comment]
Yeah this doesn't mean anything to me.
I can only offer more trial and error.

This time I switched to software flow control & I added a check if there's data to read on the serial port not sure why that would do anything.
I noticed checking if bytes are available causes IOCTL_SERIAL_GET_COMMSTATUS & reading the flags causes IOCTL_SERIAL_GET_MODEMSTATUS.
I doubt jfp or xtp do anything special on that low level.
https://ci.appveyor.com/project/gagax1234/openfunscripter/builds/37665373/artifacts

**Comment by f86k** [comment]
> I noticed checking if bytes are available causes IOCTL_SERIAL_GET_COMMSTATUS & reading the flags causes IOCTL_SERIAL_GET_MODEMSTATUS.

On this build I was able to see some debug info that was being sent by the ESP32. When it crashes during script playback, something is causing it to reset with it reporting "rst:0x1 (POWERON_RESET)".


I tried connecting with Arduino Serial Monitor and sending "L0990". This worked and the ESP32 received the command without crashing.
![image](https://user-images.githubusercontent.com/76853493/107279374-95d00a80-6a1c-11eb-917b-89901df779ac.png)

Looks like the only things missing from OFS are "SET_WAIT_MASK" and "WAIT_ON_MASK" but there's also no guarantee that something else (invisible to the serial monitor) is causing the crashes.
I think we're getting close to finding the issue, so hopefully the somewhat tedious trial and error pays off. 
I'm not an experienced programmer so this question may be obvious: is there some way of just dropping in a new serial library/module into OFS as a nuclear solution?

**Comment by gagax1234** [comment]
Well here's a completely different library.

https://ci.appveyor.com/project/gagax1234/openfunscripter/builds/37675436/artifacts

**Comment by f86k** [comment]
It works! No crashing and the ESP32 is receiving the data.

**Comment by gagax1234** [comment]
Great! Not gonna lie I didn't have high hopes but if it works it works.
Thank you for your patience with me 😄 
I'll keep this open till I do a 1.1.6 release.

**Comment by gagax1234** [comment]
https://github.com/gagax1234/OpenFunscripter/releases/tag/1.1.6
