### ISSUE TITLE
Heatmap vs video file name with ' in it

### ISSUE THREAD

**Issue by scriptingsentinel** [gagax1234/OpenFunscripter#9]
If the video file name contains the ' character then the suggested file name for the heatmap will be _INVALID DEFAULT_PATH WITH QUOTES.png_. Maybe escaping some (for file names) valid special characters? 

Example: _18VR-Romy Indy - Shop 'til You Pop - 5K 180_3dh - 2048p_FAST.mp4_

**Comment by gagax1234** [comment]
You really find all the bugs, keep it up 😁 

I looked at the libraries code and it looks like tinyfiledialogs falls back to that name whenever it finds (single or double) quotes in the path provided so all I really could do was replace quotes with spaces.
I'm just glad it had nothing to do with encoding this time.

0b20dd78d0d359ab4b6c227672b04857e0768f8b
